In [ ]:
import numpy as np

In [ ]:
len(dir(np))

532

In [ ]:
a=np.array([1,2,3,4,5])
print(a)
print(a.ndim)
print(a.shape)

[1 2 3 4 5]
1
(5,)


In [ ]:
t=[]
for i in range(1,11):
  t.append(i)
y=np.array(t)
print(y)
print(y.ndim)
print(y.shape)

[ 1  2  3  4  5  6  7  8  9 10]
1
(10,)


In [ ]:
#2d
f=np.array([[1,2,3],[10,21,33],[7,9,8]])
print(f)
print(f.ndim)
print(f.shape)

[[ 1  2  3]
 [10 21 33]
 [ 7  9  8]]
2
(3, 3)


In [ ]:
#1d to 2d
f=np.array([10,11,5,6,8,9])
print(f)
print(f.ndim)
print(f.shape)
t=f.reshape(3,2)
print(t)
print(t.ndim)
print(t.shape)


[10 11  5  6  8  9]
1
(6,)
[[10 11]
 [ 5  6]
 [ 8  9]]
2
(3, 2)


In [ ]:
#arange
f=np.arange(1,11)
print(f)
print(f.ndim)
print(f.shape)


[ 1  2  3  4  5  6  7  8  9 10]
1
(10,)


In [ ]:
#convert 1d to 2d
f=np.arange(1,11)
print(f)
print(f.ndim)
print(f.shape)

v=f.reshape(2,5)
print(v)
print(v.ndim)


[ 1  2  3  4  5  6  7  8  9 10]
1
(10,)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2


In [ ]:
f=np.arange(1,11).reshape(2,5)
print(f)
print(f.ndim)
print(f.shape)
print(f[0][1])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2
(2, 5)
2


In [ ]:
#1d convrt to 3d
f=np.arange(1,11)
print(f)
print(f.ndim)
print(f.shape)

v=f.reshape(2,1,5)
print(v)
print(v.ndim)


[ 1  2  3  4  5  6  7  8  9 10]
1
(10,)
[[[ 1  2  3  4  5]]

 [[ 6  7  8  9 10]]]
3


In [ ]:
#1d to 3d conversion
f=np.arange(1,61).reshape(5,2,6)
print(f)
print(f.ndim)
print(f.shape)
print(f[2][0][1])






[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]]

 [[13 14 15 16 17 18]
  [19 20 21 22 23 24]]

 [[25 26 27 28 29 30]
  [31 32 33 34 35 36]]

 [[37 38 39 40 41 42]
  [43 44 45 46 47 48]]

 [[49 50 51 52 53 54]
  [55 56 57 58 59 60]]]
3
(5, 2, 6)
26


In [ ]:
#reahape(1,-1)
f=np.array([1,2,5,6,7])
print(f)
print(f.ndim)
print(f.shape)

v=f.reshape(1,-1)
print(v)
print(v.ndim)


[1 2 5 6 7]
1
(5,)
[[1 2 5 6 7]]
2


In [ ]:
f=np.array([1,11,12,3,9,10])
print(f)
print(f.ndim)
print(f.shape)

v=f.reshape(-1,1)
print(v)
print(v.ndim)


[ 1 11 12  3  9 10]
1
(6,)
[[ 1]
 [11]
 [12]
 [ 3]
 [ 9]
 [10]]
2


In [ ]:
#2d to 3d
a=np.array([[1,2,3,],[10,23,45],[11,22,44]])
print(a)
print(a.ndim)
print(a.shape)
b=a.reshape(1,3,3)
print(b)
print(b.ndim)
print(b.shape)
print(b.size)

[[ 1  2  3]
 [10 23 45]
 [11 22 44]]
2
(3, 3)
[[[ 1  2  3]
  [10 23 45]
  [11 22 44]]]
3
(1, 3, 3)
9


In [ ]:
#1d to 2dto 3d
s=np.arange(1,31)
print(s)
print(s.ndim)
print(s.shape)
b=s.reshape(6,5)
print(b)
print(s.ndim)
print(s.shape)
t=s.reshape(5,2,3)
print(t)
print(s.ndim)
print(s.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
1
(30,)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
1
(30,)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]]]
1
(30,)


In [ ]:
import numpy as np


zeros

In [ ]:
a=np.array([1,3,4,5,67,8,9])
a=np.zeros((1,7))
print(a)

[[0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
a=np.arange(1,11)
a=np.zeros((5,6))
print(a)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [ ]:
a=np.arange(1,11)
a=np.zeros((3,4),dtype=np.int32)
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
#ones
a=np.arange(1,11)
a=np.ones((5,6))
print(a)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [ ]:
a=np.arange(1,11)
a=np.ones((5,6),dtype=np.int64)
print(a)

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


In [ ]:
#full
a=np.arange(1,11)
a=np.full((5,6,),7)
print(a)

[[7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]]


In [ ]:
#eye
a=np.array([1,11,8,9])
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
a=np.arange(1,11)
a=np.eye(5,5,dtype=int)
print(a)
a

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
a=np.arange(1,11)
a=np.eye(5,dtype=np.int32)
print(a)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [ ]:
#diagonal
a=np.diag((1,2,9))
print(a)

[[1 0 0]
 [0 2 0]
 [0 0 9]]


In [ ]:
a=np.array([1,2,3,4])
a=np.diag(())
print(a)

[]


In [ ]:
#random>randint
a=np.arange(1,11)
a=np.random.randint(1,11,6)
print(a)

[8 5 6 3 1 5]


In [ ]:

a=np.random.randint((5,6,2))
print(a)

[3 1 0]


In [ ]:
#randaom
a=np.random.random((5,6))
print(a)

[[0.73961994 0.20720314 0.09603363 0.37205846 0.57637248 0.10008609]
 [0.58972272 0.42021307 0.50444184 0.51991964 0.16060227 0.55262078]
 [0.60146424 0.0607225  0.57118339 0.99466047 0.03412133 0.01075757]
 [0.5221839  0.79813471 0.80680349 0.18477057 0.35357312 0.42624494]
 [0.89433804 0.35920249 0.74741397 0.58591406 0.79793267 0.9154221 ]]


In [ ]:
#rand
a=np.random.rand(1,11)

print(a)

[[0.3824915  0.74849629 0.78340088 0.91393821 0.86582578 0.93716454
  0.71227635 0.5927568  0.01095822 0.36844228 0.98844148]]


In [ ]:
#randn
a=np.random.randn(5,6)
print(a)

[[ 1.88170633 -1.04094722 -1.20151146  0.8262786  -0.09723411  0.09098758]
 [ 1.30920493 -0.43149759  1.05606191  0.36808125  0.77767476 -0.93079322]
 [-0.15750629 -1.43190576  0.34066855 -0.09329369  1.88915138 -0.45729787]
 [-0.84938634  1.33485148 -1.09804882 -0.13675892 -0.706883    1.11995439]
 [-1.78130775  0.76969142 -0.10684714 -1.24995913  0.0038355   0.81004577]]


In [ ]:
#axis=1->row
#axis=0->colum
a=np.arange(1,11)
print(a)
a=np.sum(a,axis=0)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]
55


In [ ]:
a=np.arange(1,10)
b=a.reshape(3,3)
print(b)
print(np.sum(b,axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 6 15 24]


In [ ]:
a=np.arange(1,10)
b=a.reshape(3,3)
print(b)
print(np.sum(b,axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[12 15 18]


In [ ]:
a=np.arange(1,10)
b=a.reshape(3,3)
print(b)
print(np.max(b,axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3 6 9]


In [ ]:
a=np.arange(1,10)
b=a.reshape(3,3)
print(b)
print(np.max(b,axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[7 8 9]


In [ ]:
a=np.arange(1,10)
b=a.reshape(3,3)
print(b)
print(np.min(b,axis=1))
print(np.min(b,axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 4 7]
[1 2 3]


In [ ]:
#sum
a=np.arange(1,10)
b=a.reshape(3,3)
print(b)
print(np.sum(b))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45


In [ ]:
#argmax
a=np.arange(1,10)
b=a.reshape(3,3)
print(b)
print(np.argmax(b))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
8


In [ ]:
#argmax
a=np.arange(1,10)
b=a.reshape(3,3)
print(b)
print(np.argmax(b,axis=1))
print(np.argmax(b))
print(np.argmax(b,axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 2 2]
8
[2 2 2]


In [ ]:
#argmin
a=np.arange(10,20)
b=a.reshape(5,2)
print(b)
print(np.argmin(b))
print(np.argmin(b,axis=1))
print(np.argmin(b,axis=0))

[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]
0
[0 0 0 0 0]
[4 4]


In [ ]:
#repeat
a=np.arange(11,21)
b=a.reshape(5,2)
print(b)
c=np.repeat(b,5,axis=1)
print(c)

[[11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]
[[11 11 11 11 11 12 12 12 12 12]
 [13 13 13 13 13 14 14 14 14 14]
 [15 15 15 15 15 16 16 16 16 16]
 [17 17 17 17 17 18 18 18 18 18]
 [19 19 19 19 19 20 20 20 20 20]]


In [ ]:
from IPython.core.application import atexit
a=np.arange(10,21)
b=a.reshape(1,-1)
print(b)
c=np.repeat(b,5,axis=0)
print(c)

[[10 11 12 13 14 15 16 17 18 19 20]]
[[10 10 10 10 10 11 11 11 11 11 12 12 12 12 12 13 13 13 13 13 14 14 14 14
  14 15 15 15 15 15 16 16 16 16 16 17 17 17 17 17 18 18 18 18 18 19 19 19
  19 19 20 20 20 20 20]]


In [ ]:
#transpose
a=np.arange(1,10)
b=a.reshape(3,3)
print(a.shape)
print(b)
print()
c=np.transpose(b)
print(c)

(9,)
[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
#concatination
a=np.arange(1,10)
b=np.arange(10,19)
a=a.reshape(3,3)
b=b.reshape(3,3)
print(a)
print()
print(b)
print('===')
c=np.concat((a,b))
print(c)


[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[10 11 12]
 [13 14 15]
 [16 17 18]]
===
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [ ]:
a=np.arange(1,10)
b=np.arange(10,20)
a=a.reshape(3,3)
b=b.reshape(10,1)
print(a)
print()
print(b)
print('===')
c=np.concat((a,b))
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]]
===


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 1

In [ ]:
#some  math operation
a=np.arange(1,10)
b=np.arange(10,19)
a=a.reshape(3,3)
b=b.reshape(3,3)
print(a)
print()
print(b)
print()

print(np.add(a,b))
print()
print(np.subtract(a,b))
print()
print(np.multiply(a,b))
print()
print(np.divide(a,b))


[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[10 11 12]
 [13 14 15]
 [16 17 18]]

[[11 13 15]
 [17 19 21]
 [23 25 27]]

[[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]

[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]

[[0.1        0.18181818 0.25      ]
 [0.30769231 0.35714286 0.4       ]
 [0.4375     0.47058824 0.5       ]]


In [ ]:
a=np.array([[1,2,3],[6,7,8],[4,5,6]])
b=np.array([[9,8,7],[3,4,5],[2,5,6,]])
print(a)
print(b)

print(np.add(a,b))
print()
print(np.subtract(a,b))
print()
print(np.multiply(a,b))
print()
print(np.divide(a,b))


[[1 2 3]
 [6 7 8]
 [4 5 6]]
[[9 8 7]
 [3 4 5]
 [2 5 6]]
[[10 10 10]
 [ 9 11 13]
 [ 6 10 12]]

[[-8 -6 -4]
 [ 3  3  3]
 [ 2  0  0]]

[[ 9 16 21]
 [18 28 40]
 [ 8 25 36]]

[[0.11111111 0.25       0.42857143]
 [2.         1.75       1.6       ]
 [2.         1.         1.        ]]


In [ ]:
#matmul
a=np.array([[1,2,3],[6,7,8],[4,5,6]])
b=np.array([[9,8,7],[3,4,5],[2,5,6,]])
print(a)
print(b)
print()
print(np.matmul(a,b))
print()

[[1 2 3]
 [6 7 8]
 [4 5 6]]
[[9 8 7]
 [3 4 5]
 [2 5 6]]

[[ 21  31  35]
 [ 91 116 125]
 [ 63  82  89]]



# numpy examples

In [ ]:
import numpy as np

t=np.array([[1,2,2],[3,5,8],[6,7,9,]])
print(t)
print(t.ndim)
print('shape of the arr:',t.shape )
print('size of the arr:',t.size)

[[1 2 2]
 [3 5 8]
 [6 7 9]]
2
shape of the arr: (3, 3)
size of the arr: 9


In [ ]:
a=np.arange(1,82).reshape(3,3,9)
print(a)
print(a[2][2][5])

[[[ 1  2  3  4  5  6  7  8  9]
  [10 11 12 13 14 15 16 17 18]
  [19 20 21 22 23 24 25 26 27]]

 [[28 29 30 31 32 33 34 35 36]
  [37 38 39 40 41 42 43 44 45]
  [46 47 48 49 50 51 52 53 54]]

 [[55 56 57 58 59 60 61 62 63]
  [64 65 66 67 68 69 70 71 72]
  [73 74 75 76 77 78 79 80 81]]]
78


In [ ]:
an_array=np.array([30,331,33])
print(type(an_array))
print(an_array.shape)
print(an_array[0],an_array[1],an_array[2])
an_array[0]=888
print(an_array)

<class 'numpy.ndarray'>
(3,)
30 331 33
[888 331  33]


In [ ]:
another=np.array([[11,21,22],[23,16,30]])
print(a)
print(another)
print("The shape is 2 rows, 3 columns: ", another.shape)  # rows x columns

print("Accessing elements [0,0], [0,1], and [1,0] of the ndarray: ", another[0, 0], ", ",another[0, 1],", ", another[1, 0])

[[[ 1  2  3  4  5  6  7  8  9]
  [10 11 12 13 14 15 16 17 18]
  [19 20 21 22 23 24 25 26 27]]

 [[28 29 30 31 32 33 34 35 36]
  [37 38 39 40 41 42 43 44 45]
  [46 47 48 49 50 51 52 53 54]]

 [[55 56 57 58 59 60 61 62 63]
  [64 65 66 67 68 69 70 71 72]
  [73 74 75 76 77 78 79 80 81]]]
[[11 21 22]
 [23 16 30]]
The shape is 2 rows, 3 columns:  (2, 3)
Accessing elements [0,0], [0,1], and [1,0] of the ndarray:  11 ,  21 ,  23


# zeros

In [ ]:
ex1=np.zeros((2,2),dtype=int)
print(ex1)

[[0 0]
 [0 0]]


full

In [ ]:
ex2=np.full((2,2),9,dtype=float)
print(ex2)

[[9. 9.]
 [9. 9.]]


eye

In [ ]:
a=np.eye(2,2,dtype=int)
print(a)
print(a[0][0])
print(a.shape)

[[1 0]
 [0 1]]
1
(2, 2)


ones

In [ ]:
a=np.ones((1,2),dtype=int)
print(a)
print(a.shape)
print(a[0])

[[1 1]]
(1, 2)
[1 1]


In [ ]:
#random
ex3=np.random.random((2,2))
print(ex3)

[[0.25799942 0.40136037]
 [0.39405282 0.42493754]]


array indexing

In [ ]:
an_array=np.array([[11,12,13,14],[20,21,22,23],[30,31,32,33]])
print(an_array)

[[11 12 13 14]
 [20 21 22 23]
 [30 31 32 33]]


In [ ]:
b=an_array[2, :3]
c=a[-1]
print(b)
print(c)

[30 31 32]
32


In [ ]:
a_slicing=an_array[:2,1:3]
print(a_slicing)


[[12 13]
 [21 22]]


np.int64(32)

In [ ]:
an_array[2][2]

np.int64(32)

In [ ]:
an_array

array([[11, 12, 13, 14],
       [20, 21, 22, 23],
       [30, 31, 32, 33]])

In [ ]:

a_slicing

array([[12, 13],
       [21, 22]])

In [ ]:
print("Before:", an_array[0, 1])   #inspect the element at 0, 1
a_slicing[0, 0] = 1000    # a_slice[0, 0] is the same piece of data as an_array[0, 1]
print("After:", an_array[0, 1])

Before: 12
After: 1000


In [ ]:
an_array=np.array([[11,12,13,14],[20,21,22,23],[30,31,32,33]])
print(an_array)
print(an_array.shape)


[[11 12 13 14]
 [20 21 22 23]
 [30 31 32 33]]
(3, 4)


In [ ]:
row=an_array[1,:]
print(row)
print(row.shape)

[20 21 22 23]
(4,)


In [ ]:
 #Slicing alone: generates an array of the same rank as the an_array
row_rank2 = an_array[1:2, :]  # Rank 2 view

print(row_rank2, row_rank2.shape)   # Notice the [[ ]]

[[20 21 22 23]] (1, 4)


In [ ]:
#We can do the same thing for columns of an array:

print()
col_rank1 = an_array[:, 1]
col_rank2 = an_array[:, 1:2]

print(col_rank1, col_rank1.shape)  # Rank 1
print()
print(col_rank2, col_rank2.shape)  # Rank 2


[12 21 31] (3,)

[[12]
 [21]
 [31]] (3, 1)


In [ ]:
#Create a new array
an_array = np.array([[11,12,13], [21,22,23], [31,32,33], [41,42,43]])

print('Original Array:')
print(an_array)

Original Array:
[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]


In [ ]:
b=np.array([[1,2],[4,5],[10,13]])
print(b)

[[ 1  2]
 [ 4  5]
 [10 13]]


In [ ]:
a=1
a

1

In [ ]:
map=1
print(map)

1


In [ ]:
filter=(b<10)
filter

array([[ True,  True],
       [ True,  True],
       [False, False]])

In [ ]:
print(b[filter])

[1 2 4 5]


datatypes

In [ ]:
ex=np.array([11,12])
print(ex.dtype)

int64


In [ ]:
ex2 = np.array([11.0, 12.0]) # Python assigns the  data type
print(ex2.dtype)

float64


In [ ]:
ex2 = np.array([11.0, 12.0]) # Python assigns the  data type
print(ex2.dtype)

float64


In [ ]:
ex2 = np.array([11.0, 12.0]) # Python assigns the  data type
print(ex2.dtype)

float64


In [ ]:
ex4 = np.array([11.1,12.7], dtype=np.int64)
print(ex4.dtype)
print()
print(ex4)

int64

[11 12]


In [ ]:
ex5 = np.array([11, 21], dtype=np.float64)
print(ex5.dtype)
print()
print(ex5)

float64

[11. 21.]


ariithmetic array operation

In [ ]:

import numpy as np

x = np.array([[111,112],[121,122]], dtype=int)
y = np.array([[211.1,212.1],[221.1,222.1]], dtype=np.float64)

print('X_array = ', x)
print()
print('y_array = ', y)

X_array =  [[111 112]
 [121 122]]

y_array =  [[211.1 212.1]
 [221.1 222.1]]


In [ ]:
print(x+y)
print()
print(np.add(x,y))

[[322.1 324.1]
 [342.1 344.1]]

[[322.1 324.1]
 [342.1 344.1]]


In [ ]:
#substact
print(x-y)
print()
print(np.subtract(x,y))

[[100.46434625 101.41699476]
 [110.         110.95463898]]

[[100.46434625 101.41699476]
 [110.         110.95463898]]


In [ ]:
#multply
print(x*y)
print()
print(np.multiply(x,y))

[[1169.45756657 1185.29658736]
 [1331.         1347.5340441 ]]

[[1169.45756657 1185.29658736]
 [1331.         1347.5340441 ]]


In [ ]:
#division
print(x/y)
print()
print(np.divide(x,y))

[[10.53565375 10.58300524]
 [11.         11.04536102]]

[[10.53565375 10.58300524]
 [11.         11.04536102]]


In [ ]:
#square root
a=np.array([4,3,6])
print(a)
print()
print(np.sqrt(a))

[4 3 6]

[2.         1.73205081 2.44948974]


In [ ]:
#exponent
print(np.exp(a))

[ 54.59815003  20.08553692 403.42879349]


statistical operations,set

In [ ]:
s=20*np.random.randn(4,5)
print(s)

[[-21.94699845  13.97437325  40.76195482  35.11856395  -6.12351191]
 [-11.11595357  18.10988294  -7.90544745  25.50582663  -1.83774055]
 [ -5.73749059  -9.56461744   8.58662971 -34.24064056 -18.34520475]
 [ 19.05378823 -31.23395471  -8.95028405  -7.26069769 -24.18043279]]


In [ ]:
arr=np.array([2,5,6])
print(arr.mean())


4.333333333333333


In [ ]:
print(sum(arr))

13


In [ ]:
#mean of row
print(s.mean(axis=1))

[ 12.35687633   4.5513136  -11.86026473 -10.5143162 ]


In [ ]:
# mean of colum
print(s.mean(axis=0))

[ -4.9366636   -2.17857899   8.12321326   4.78076308 -12.6217225 ]


In [ ]:
#sum of all eliments
print(sum(s))

[-19.74665438  -8.71431596  32.49285303  19.12305232 -50.48689   ]


In [ ]:
#median
print(np.median(s,axis=1))

[13.97437325 -1.83774055 -9.56461744 -8.95028405]


In [ ]:
arr=np.array([[4,5,6],[7,8,9]])
print(arr)

[[4 5 6]
 [7 8 9]]


In [ ]:
print(sum(arr))

[11 13 15]


In [ ]:
np.median(arr)

np.float64(6.5)

In [ ]:
print(np.median(arr,axis=1))

[5. 8.]


In [ ]:
print(arr.mean())

6.5


In [ ]:
arr.sum(axis=0)

array([11, 13, 15])

In [ ]:
arr.sum(axis=1)

array([15, 24])

sorting

In [ ]:
arr=np.random.randn(10)
print(arr)



[ 0.05874807  0.74196024 -0.19111903  1.37721579  0.9254259  -0.57778431
  0.16828476  1.17779546  0.3353679  -0.05113472]


In [ ]:
# create cpy sort
sorted=np.array(arr)
sorted.sort()
print(sorted)
print()
print(arr)

[-0.57778431 -0.19111903 -0.05113472  0.05874807  0.16828476  0.3353679
  0.74196024  0.9254259   1.17779546  1.37721579]

[ 0.05874807  0.74196024 -0.19111903  1.37721579  0.9254259  -0.57778431
  0.16828476  1.17779546  0.3353679  -0.05113472]


In [ ]:
a=[1,2,3,4,5]
a.sort(reverse=True)
a

[5, 4, 3, 2, 1]

In [ ]:
# inplace sort
arr.sort()
print(arr)

[-0.57778431 -0.19111903 -0.05113472  0.05874807  0.16828476  0.3353679
  0.74196024  0.9254259   1.17779546  1.37721579]


finding unique eliments

In [ ]:
a=np.array([1,2,3,3,4,4,1])
print(np.unique(a))

[1 2 3 4]


# set operation with np.arry datatype

In [ ]:
a=np.array(['red','green','blue'])
b=np.array(['yellow','red','blue'])
print(a,b)

['red' 'green' 'blue'] ['yellow' 'red' 'blue']


In [ ]:
print(np.intersect1d(a,b))

['blue' 'red']


In [ ]:
print(np.union1d(a,b))

['blue' 'green' 'red' 'yellow']


In [ ]:
print(np.setdiff1d(a,b))

['green']


In [ ]:
print(np.in1d(a,b))

[ True False  True]


/tmp/ipython-input-514389329.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  print(np.in1d(a,b))


broadcasting

In [ ]:
import numpy as np

start = np.zeros((4,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:

y = start + add_rows  # add to each row of 'start' using broadcasting
print(y)

NameError: name 'add_rows' is not defined

In [ ]:
 #create a rank 1 ndarray with 3 values
add_rows = np.array([1, 0, 2])
print(add_rows)

[1 0 2]


In [ ]:
 #create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T

print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [ ]:
# add to each column of 'start' using broadcasting
y = start + add_cols
print(y)

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [ ]:
import numpy as np

 #this will just broadcast in both dimensions
add_scalar = np.array([1])
print(start+add_scalar)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#reate our 3x4 matrix
arrA = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arrA)

In [ ]:
#question sum all diagonal
import numpy as np

arr=np.array([[1,7,9],[2,4,8],[3,6,5]])
print(arr)
f=0
if arr.shape[0] ==arr.shape[1]:
  s=0
  for i in arr:
    f=f+i[s]
    s=s+1
  print(f)
else:
  print(f'diagonal adding not possible')







[[1 7 9]
 [2 4 8]
 [3 6 5]]
10


example from slides

In [ ]:
# create our 3x4 matrix
arrA = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arrA)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
#create 4x1matreis
arrB=np.array([1,0,2,0])
print(arrB)

[1 0 2 0]


In [ ]:
print(arrA+arrB)

[[ 2  2  5  4]
 [ 6  6  9  8]
 [10 10 13 12]]


binary format

In [ ]:
a=np.array([23.23,24.24])
print(a)

[23.23 24.24]


In [ ]:
np.save('an_array',a)

In [ ]:
oad

In [ ]:
np.load('an_array.npy')

array([23.23, 24.24])

Dot Product on Matrices and Inner Product on Vectors:

In [ ]:
a = np.array([[1,1],[2,2]])
b = np.array([[2,3],[4,2]]) # tensorflow we can discuss

print(a.dot(b))
print()
#print(np.dot(a, b))

[[ 6  5]
 [12 10]]



In [ ]:
a = np.array([[1,1],[2,2]])
b = np.array([[2,3],[4,2]]) # tensorflow we can discuss

print(a.dot(b))
print()
print(np.dot(a,b))
#print(np.dot(a, b))

[[ 6  5]
 [12 10]]

[[ 6  5]
 [12 10]]


In [ ]:
a = np.array([[1,1],[2,2]])
b = np.array([[2,3],[4,2]]) # tensorflow we can discuss

print(a.dot(b))
print()
#print(np.dot(a, b))
c = np.dot(a, b)       # matrix multiplication
total = np.sum(c)      # sum all elements
print(total)

[[ 6  5]
 [12 10]]

33


In [ ]:
# revese diagonal sum
a=np.array([[1,7,9,10],[2,4,8,20],[3,6,5,30],[1,2,3,4]])
print(a)
f=0
if a.shape[0]==a.shape[1]:
   s=-1
   for i in a:
     f=f+i[s]
     s=s-1
   print(f)
else:
  print(f'diagonal adding not possible')





[[ 1  7  9 10]
 [ 2  4  8 20]
 [ 3  6  5 30]
 [ 1  2  3  4]]
25


In [ ]:
# summ of colums
a=np.array([[1,7,9,10],[2,4,8,20],[3,6,5,30],[1,2,3,4]])
print(a)
s=0
for i in range(len(a)):
    for j in a:
      s=s+j[i]


print(s)



[[ 1  7  9 10]
 [ 2  4  8 20]
 [ 3  6  5 30]
 [ 1  2  3  4]]
115


In [ ]:
#a=np.array([[1,7,9,10],[2,4,8,20],[3,6,5,30],[1,2,3,4]])
print(a)
row_sum=np.sum(a,axis=1)
print(row_sum)


[[ 1  7  9 10]
 [ 2  4  8 20]
 [ 3  6  5 30]
 [ 1  2  3  4]]
[27 34 44 10]


In [ ]:
#using numpy can we generate colors(if yes) then how is that possible

In [ ]:
a=[]
for i in range(1,11):
  a.append(i)
print(a)
b=[1, 1,2 ,'kmal']
print(b)
print(a.ndim)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[1, 1, 2, 'kmal']


AttributeError: 'list' object has no attribute 'ndim'

In [ ]:
a=[1,2,4]
print(type(a))

<class 'list'>


In [ ]:
a=[1,2,4]
print(type(a))
print(a.ndim)

<class 'list'>


AttributeError: 'list' object has no attribute 'ndim'

In [ ]:
for i in range(1,11):
  print(i,end=' ')

1 2 3 4 5 6 7 8 9 10 

In [ ]:
a=np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a = np.array([1,2,3,4])
b = np.array([[1] , [2]])
c = np.array([[[1,2,3]]])

In [ ]:
print(a.ndim)
print(b.ndim)
print(c.ndim)

1
2
3


In [ ]:
a=np.arange(1,11)
print(a)
a.ndim

[ 1  2  3  4  5  6  7  8  9 10]


1

In [ ]:
a=np.arange(1,11,2)
a

array([1, 3, 5, 7, 9])

In [ ]:
a=np.arange(1,11,2,dtype=int)
print(a)

array([1, 3, 5, 7, 9])

linspace()

In [3]:
import numpy as np
f=np.linspace(1,9)
print(f)

[1.         1.16326531 1.32653061 1.48979592 1.65306122 1.81632653
 1.97959184 2.14285714 2.30612245 2.46938776 2.63265306 2.79591837
 2.95918367 3.12244898 3.28571429 3.44897959 3.6122449  3.7755102
 3.93877551 4.10204082 4.26530612 4.42857143 4.59183673 4.75510204
 4.91836735 5.08163265 5.24489796 5.40816327 5.57142857 5.73469388
 5.89795918 6.06122449 6.2244898  6.3877551  6.55102041 6.71428571
 6.87755102 7.04081633 7.20408163 7.36734694 7.53061224 7.69387755
 7.85714286 8.02040816 8.18367347 8.34693878 8.51020408 8.67346939
 8.83673469 9.        ]


In [4]:
f=np.linspace(1,9,2)
print(f)

[1. 9.]


In [6]:
f=np.linspace(10,20,9)
print(f)

[10.   11.25 12.5  13.75 15.   16.25 17.5  18.75 20.  ]


In [10]:
f=np.ones((1,9))
print(f)

[[1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [12]:
f=np.zeros((1,9))
print(f)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [14]:
f=np.ones((3,3))
print(f)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [13]:
f=np.zeros((3,3))
print(f)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [16]:
range(1,11)

range(1, 11)

In [17]:
f=list[1,3,4]
print(f.ndim)

AttributeError: type object 'list' has no attribute 'ndim'

In [18]:
a=np.arange(1,11)
a[5:]=60
print(a)

[ 1  2  3  4  5 60 60 60 60 60]


In [21]:
print(list(range(100)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In [24]:
a=np.arange(1,11)
ab=a[::-1]
print(a)
print(ab)

[ 1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1]


In [25]:
print(list(range(10,91,5)))

[10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90]


In [27]:
from IPython.display import Image
Image("C://Users//korla//Desktop//img//numpy one.PNG",width=800,height=600)

FileNotFoundError: No such file or directory: 'C://Users//korla//Desktop//img//numpy one.PNG'

FileNotFoundError: No such file or directory: 'C://Users//korla//Desktop//img//numpy one.PNG'

<IPython.core.display.Image object>

In [29]:
a=np.arange(1,9)
print(a)

[1 2 3 4 5 6 7 8]


In [31]:
a=np.arange(1,9).reshape(2,4)
print(a)
a.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [37]:

a=np.arange(1,61).reshape(10,6)
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]
 [49 50 51 52 53 54]
 [55 56 57 58 59 60]]


In [41]:
a[4][4]


np.int64(29)

In [42]:
a[6][4]

np.int64(41)

In [43]:
import numpy as np
b=np.arange(1,61).reshape(5,2,6)
b

array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]],

       [[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36]],

       [[37, 38, 39, 40, 41, 42],
        [43, 44, 45, 46, 47, 48]],

       [[49, 50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59, 60]]])

In [46]:
b[0][0][5]

np.int64(6)

In [49]:

b=np.cos(a)
b

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
         0.96017029],
       [ 0.75390225, -0.14550003, -0.91113026, -0.83907153,  0.0044257 ,
         0.84385396],
       [ 0.90744678,  0.13673722, -0.75968791, -0.95765948, -0.27516334,
         0.66031671],
       [ 0.98870462,  0.40808206, -0.54772926, -0.99996083, -0.53283302,
         0.42417901],
       [ 0.99120281,  0.64691932, -0.29213881, -0.96260587, -0.74805753,
         0.15425145],
       [ 0.91474236,  0.83422336, -0.01327675, -0.84857027, -0.90369221,
        -0.12796369],
       [ 0.76541405,  0.95507364,  0.26664293, -0.66693806, -0.98733928,
        -0.39998531],
       [ 0.5551133 ,  0.99984331,  0.52532199, -0.43217794, -0.99233547,
        -0.64014434],
       [ 0.30059254,  0.96496603,  0.7421542 , -0.16299078, -0.91828279,
        -0.82930983],
       [ 0.02212676,  0.85322011,  0.89986683,  0.11918014, -0.77108022,
        -0.95241298]])

In [50]:
aa=np.diag([1,2,3,4,5]) # diagonal function
aa

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [58]:
a=np.arange(1,11).reshape(5,2)
print(a)
b=np.ravel(a)
b

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
a.T

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [60]:
import numpy as np
n = np.zeros((4,4))
print(n)
print("%d bytes" % (n.size * n.itemsize))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
128 bytes
